# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 47c33f4a1ca369168841ac586b8e1b0f8125293e61c560e5adf165768aff79e0142943481f7e7aa6cad7835cc57da7e69be5a93974303ba67f9bba4d9a847fc2

test:
  secret_key_base: b253c5d541ac89b4c72ed0744c3de41d5e01bb77e7c9507d38a4818dfb26cf77019fc29b43e95a32a8575299acecf1b1afc5e5dabe94273ebdd62a1a8701f889

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
